#ifndef GUARD_CONSTANTS_FIRE_RED_LLM_CHALLENGE_H
#define GUARD_CONSTANTS_FIRE_RED_LLM_CHALLENGE_H

#define FIRE_RED_LLM_CHALLENGE_SEED 0xF17E
#define FIRE_RED_LLM_CHALLENGE_LEVEL_CAP 14

#define FIRE_RED_LLM_CHALLENGE_STATE_NONE   0
#define FIRE_RED_LLM_CHALLENGE_STATE_ACTIVE 1
#define FIRE_RED_LLM_CHALLENGE_STATE_WON    2
#define FIRE_RED_LLM_CHALLENGE_STATE_LOST   3

#define FIRE_RED_LLM_CHALLENGE_SCENE_NONE  0
#define FIRE_RED_LLM_CHALLENGE_SCENE_INTRO 1
#define FIRE_RED_LLM_CHALLENGE_SCENE_SHOWN 2

#endif // GUARD_CONSTANTS_FIRE_RED_LLM_CHALLENGE_H
